apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  namespace: ${parameters.namespace}
  labels:
    app: demo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
        - name: demo-api
          image: armory/demo-api
          args: ['-bucket', '${parameters.env_name}-bucket']
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: demo-api
  namespace: ${parameters.namespace}
spec:
  selector:
    app: demo-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer