apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    strategy.spinnaker.io/versioned: 'true'
  name: jobjob
  namespace: ethan-dev
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: test
          image: nginx:alpine
          command:
          -  echo
          - "hello world"
